codecov:
  strict_yaml_branch: master
coverage:
  changes: true
  round: down
  precision: 2
  status:
    project:
      default:
        target: 60%
        threshold: 0%
        flags:
          - "unittest"
    patch:
      default:
        target: 80%
        threshold: 0%
        flags:
          - "unittest"

